### ISSUE TITLE
Delete Garden + Gravestone Entrypoint and Garden Pages

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#151]
Delete a garden or entrypoint

Things to think about:
- Best practices for DOI when garden/entrypoint is deleted
- redirects

**Comment by OwenPriceSkelly** [comment]
https://support.datacite.org/docs/tombstone-pages

**Comment by kjschmidt913** [comment]
Blocked on the backend. Hayden has a PR in to unblock

**Comment by kjschmidt913** [comment]
unblocked on backend. Not priority this week

**Comment by kjschmidt913** [comment]
Priority this week after Monday/Tuesday
