### ISSUE TITLE
Design Style Guide

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#17]
Make the basic v0 style guide to be iterated upon later. 

- [ ] outlining the high level structure for the guide
- [ ] find existing document of styles and incorporate them into the guide
- [ ] populating what we already know into the structure

Future: can focus more on sections of style guide

**Comment by pillkim** [comment]
Create a rough style guide for Garden (to be refined later). Include:
- Project Tone / Personality
- Typography
- Basic Color Schemes, color use

**Comment by kjschmidt913** [comment]
Start with Jennifer's designs
Move on to pages you are designing

**Comment by WillEngler** [comment]
Whole thing isn't done, but skeleton is in and ready for review.

**Comment by kjschmidt913** [comment]
Phillip is posting the style guide in the garden slack for comments. The style guide will be a living document this summer. This story was for starting it and beginning the structure. It is complete.
