### ISSUE TITLE
Point the frontend to the new backend search route

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden-frontend#205]
Sister ticket to https://github.com/Garden-AI/garden-backend/issues/161

We have a good prototype of this across BE and FE. This ticket tracks the work of any further tweaks needed to productionize and ship it.

**Comment by shane-jung** [comment]
Just waiting for one change on backend (adding support for sorting), at which point I'll add the corresponding changes on the frontend and mark my PR as ready
