### ISSUE TITLE
Production Ready Garden v0

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#25]
Make Garden website production ready!

Metadata stuff: (this is [its own issue](https://github.com/Garden-AI/garden/issues/194), but is important for this)
1. Chase prioritizes metadata that we don't currently have on the backend by looking at the front end design
2. Garden team meets to figure out what metadata we can add at this time
3. Backend team adds these fields

Website stuff:
1. Get rid of features we don't have yet (just comment out for now)
2. Use data from API call instead of dummy data

**Comment by kjschmidt913** [comment]
I know we said "comment out" originally, but Will had the great idea of just not rendering them!

My interpretation of this suggestion is that you need to take the code you don't want rendered, and put it into components that we can put in later when we're ready. (Will if you see this and that's not what you meant, please chime in)

**Comment by WillEngler** [comment]
Chase suggests: should probably be some sort of error page/redirect for a wrong DOI

**Comment by kjschmidt913** [comment]
Blocked until metadata changes are complete
