### ISSUE TITLE
Update the homepage with new styling

### ISSUE THREAD

**Issue by pillkim** [Garden-AI/garden-frontend#43]
Do this after reviewing and getting feedback on future UI changes.

Changes to implement:

- [x] Fix logo resolutions
- [ ] animate featured gardens
- [ ] create new featured gardens component
- [x] make responsive links
- [x] Add link to new accelerate page
- [x] fix bottom banner spacing and spacing for separate breakpoints
- [x] make headers more clear
- [x] rethink header banner image and setup
- [x] rethink text blocks ?

**Comment by kjschmidt913** [comment]
@pillkim is this the PR you submitted a few weeks ago? Are these all done or just the boxes checked were in that PR?
