### ISSUE TITLE
Point thegardens.ai to prod datastores

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden-frontend#44]
Success criteria:
- ~The real website is deployed on the real URL~ (KJ did this already)
- It is pointing to the prod datastores created in https://github.com/Garden-AI/garden/issues/154 (ie, this version of the website will not be filled with e2e test gardens)

**Comment by kjschmidt913** [comment]
Real website is now deployed to real URL

**Comment by WillEngler** [comment]
Cool, updated ticket with narrower scope
