### ISSUE TITLE
Update website description for link previews

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#48]
right now the link description is "Web site created using create-react-app". Find that in the code and update it was a catchy little phrase about Garden. This can be taken from somewhere on the homepage or you can workshop one with the team in slack.

**Comment by kjschmidt913** [comment]
@pillkim I remember you were working on social previews. This was part of that work, correct? So I can close this issue?

**Comment by pillkim** [comment]
should be good to be closed now!
