### ISSUE TITLE
Do basic Globus login

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden-frontend#8]
Add an OAuth login flow against Globus Auth and call the Garden backend and/or one of the Globus services that Garden uses (like Search)

# Assumptions:
1. We should evaluate and ideally pull in the new Globus JS SDK to handle most of the login work.
2. Whatever way we store the login state here won't necessarily be _the_ state management solution we go with. (One step at a time)

# Acceptance Criteria
Given I am a Globus user and I go to a hidden route in the Garden frontend, when I click the login button then I will go through a redirect flow to Globus Auth and be returned to a page that has some data from the Garden backend.

**Comment by WardLT** [comment]
There's a Globus JS sdk!? 🤯

**Comment by WillEngler** [comment]
@WardLT It's not released/finished yet but we're having an early look 😄
