### ISSUE TITLE
Design Garden landing page

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#9]
The Garden Landing page needs to look good and include:
- What is Garden
- What problem does it solve
- Links to associated projects (Foundry, MDF, Globus)
- Link to viewing Gardens

This is a design task. Design this page and fill in with Lorem Ipsem. The above suggestions are to keep in mind to have room for. Jennifer's designs for reference: https://miro.com/app/board/uXjVPXpw5XA=/

**Comment by ascourtas** [comment]
There is an existing bare bones mock up/layout for this -- need to connect Chase with mentors about what should stay and what should go. 

But, feel free to start from scratch!
