### ISSUE TITLE
render metadata for related datasets

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#92]
There's been a change in how we're storing related datasets for entrypoints. Make sure these are referenced correctly on the entrypoint page and on the garden page.

**Comment by kjschmidt913** [comment]
@shane-jung is on this issue. Will assign him officially when he joins the org

**Comment by shane-jung** [comment]
## Updated Garden Page

![Screenshot 2024-05-28 153946](https://github.com/Garden-AI/garden-frontend/assets/71043373/e781f3a0-ee42-4b54-b46c-ec0cb1777421)

## Updated Entrypoint Page

![image](https://github.com/Garden-AI/garden-frontend/assets/71043373/2df3070c-709c-46a4-902c-08f958bd04ba)

Most gardens do not yet have datasets associated with them-- please see "Dummy Garden" and the associated entrypoint "Iris Classifier (with bonus data)" to see an example.
