### ISSUE TITLE
Hide Draft DOI’s on entrypoint and Garden pages

### ISSUE THREAD

**Issue by kjschmidt913** [Garden-AI/garden-frontend#95]
Right now, if someone publishes a Garden or entrypoint with a draft DOI, the DOI is displayed on the page. The DOI should be official before we publish it on our website. 

1. Look through the Garden and Entrypoint metadata to find how DOIs are marked as a draft or official. If it's not obvious, ask Owen where you can find this.
2. Write the logic on the frontend to hide draft DOIs

**Comment by OwenPriceSkelly** [comment]
should be unblocked on the backend!
